wrapper: idea for wsl2

diff --git a/bin/wrapper/idea b/bin/wrapper/idea
--- a/bin/wrapper/idea
+++ b/bin/wrapper/idea
@@ -1,2 +1,38 @@
 #!/bin/bash
-"/c/Program Files/JetBrains/IntelliJ IDEA 2022.2.1/bin/idea64.exe" "$@"
+
+declare -g IDEA_EXECUTABLE="${IDEA_EXECUTABLE:-}"
+
+find-idea() {
+    declare current
+    if [[ -x "$IDEA_EXECUTABLE" ]] ; then
+        echo "$IDEA_EXECUTABLE"
+        return 0
+    fi
+    current="$(which idea64.exe)"
+    [[ -x "$current" ]] && { echo "$current"; return 0; }
+    current="$(which idea.bat)"
+    current="$(dirname "$current")/idea64.exe"
+    [[ -x "$current" ]] && { echo "$current"; return 0; }
+
+    current="$(get-windows-env PROGRAMFILES)/JetBrains"
+    current="$(find "$current" -mindepth 1 -maxdepth 1 -iname '*IDEA*'|head -n 1)"
+    current="$current/bin/idea64.exe"
+    [[ -x "$current" ]] && { echo "$current"; return 0; }
+
+    return 1
+}
+
+IDEA_EXECUTABLE="$(find-idea)" || {
+    echo "Could not find idea executable." 1>&2
+    return 1
+}
+
+# On wsl2 we need to use the windows environment via powershell
+# or idea just doesn't launch.
+if grep -qi microsoft /proc/version ; then
+    # FIXME: We might need to escape the arguments properly here
+    powershell.exe -Command "Start-Process" \""$(wslpath -wa "$IDEA_EXECUTABLE")"\" "$@"
+else
+    "$IDEA_EXECUTABLE" "$@"
+fi
+
